import AssertionError from "./AssertionError.js";
import deepEqual from "./deepEqual.js";
import deepStrictEqual from "./deepStrictEqual.js";
import doesNotMatch from "./doesNotMatch.js";
import doesNotReject from "./doesNotReject.js";
import doesNotThrow from "./doesNotThrow.js";
import equal from "./equal.js";
import fail from "./fail.js";
import ifError from "./ifError.js";
import match from "./match.js";
import notDeepEqual from "./notDeepEqual.js";
import notDeepStrictEqual from "./notDeepStrictEqual.js";
import notEqual from "./notEqual.js";
import notStrictEqual from "./notStrictEqual.js";
import ok from "./ok.js";
import rejects from "./rejects.js";
import strictEqual from "./strictEqual.js";
import throws from "./throws.js";
import strict from "./strict.js";

module.exports = exports = ok.bind();
exports.AssertionError = AssertionError;
exports.deepEqual = deepEqual;
exports.deepStrictEqual = deepStrictEqual;
exports.doesNotMatch = doesNotMatch;
exports.doesNotReject = doesNotReject;
exports.doesNotThrow = doesNotThrow;
exports.equal = equal;
exports.fail = fail;
exports.ifError = ifError;
exports.match = match;
exports.notDeepEqual = notDeepEqual;
exports.notDeepStrictEqual = notDeepStrictEqual;
exports.notEqual = notEqual;
exports.notStrictEqual = notStrictEqual;
exports.ok = ok;
exports.rejects = rejects;
exports.strictEqual = strictEqual;
exports.throws = throws;
exports.strict = strict;
